=head1 ABOUT

This document talks about the test suite, how it is arranged, how existing
tests are organized and how new tests are added.

=head1 Test Directories

=over 4

=item C<t/>

Tests in the base directory are simple tests for sanity. They prove that the
basic elements are working and that we can proceed to more advanced tests. These
sanity tests include proofs that the TAP testing functions are operational.

=item C<t/syntax/>

Tests in the syntax directory test more of the syntax of M, using the TAP testing
functions.

=item C<t/functions/>

Tests in the functions directory test the various library functions. These functions
may be builtin functions (F<src/builtins/>) and toolbox functions (F<toolbox/>).
The one ommission is that it does not test the TAP functions, which are already
tested in the base directory.

=back
